steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/frdemo-378609/fr-test-demo:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/frdemo-378609/fr-test-demo:$SHORT_SHA']
