steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/frdemo-378609/fr-test-demo:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/frdemo-378609/fr-test-demo:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'fr-test-demo', '--platform=managed', '--image=gcr.io/frdemo-378609/fr-test-demo:$SHORT_SHA', '--region=us-central1']

